_wandb:
    value:
        cli_version: 0.22.0
        e:
            0ao1j82o83uyuayca0w3qco8rmv70h1d:
                codePath: example.py
                codePathLocal: example.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "662271307776"
                        used: "59580440576"
                email: alexdopico2001@gmail.com
                executable: /home/alejandrodopico/miniconda3/envs/fedheonn/bin/python
                git:
                    commit: 29ca5b7224b01b6d04bbe3f21ae399048efb2481
                    remote: git@github.com:AlejandroDopico2/FedHEONNLib.git
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-3a3a85ba-ea25-041c-ec25-f033d1f47949
                host: pop-os
                memory:
                    total: "67287027712"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/alejandrodopico/fedhenet/example.py
                python: CPython 3.11.13
                root: /home/alejandrodopico/fedhenet
                startedAt: "2025-09-26T08:57:24.382208Z"
                writerId: 0ao1j82o83uyuayca0w3qco8rmv70h1d
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 15
                - 16
            "4": 3.11.13
            "5": 0.22.0
            "10":
                - 20
            "12": 0.22.0
            "13": linux-x86_64
config_path:
    value: configs/sim_cifar_dirichlet.toml
