seed = 42

[dataset]
name = "cifar10"
root = "./data"
split = "dirichlet"
alpha = 0.3
num_clients = 2
subsample_fraction = 0.25

[extractor]
type = "resnet18"
weights = "default"

[coordinator]
num_classes = 10
device = "cuda"

[client]
device = "cuda"
batch_size = 128

[communication]
encrypted = false
broker = "localhost"
port = 1883

[logging]
enable_wandb = false
enable_codecarbon = false