[dataset]
name = "cifar10"
root = "./data"
split = "dirichlet"
alpha = 0.3
subsample_fraction = 0.1
num_clients = 100
train = true

[extractor]
type = "resnet18"
weights = "default"

[coordinator]
num_classes = 10
device = "cuda"

[client]
device = "cuda"
batch_size = 128

[communication]
encrypted = false
broker = "localhost"
port = 1883

[logging]
enable_wandb = true
enable_codecarbon = true